import requests
import base64
from email.message import EmailMessage
import smtplib

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

from config import GEMINI_API_KEY, EMAIL_APP_PASSWORD
from prompt import get_prompt

# Collects the information needed to create the job application.
def get_info():
    company_name = input('Company name: ')
    company_description = input('Company description: ')
    company_email = input('Company email: ')
    job_position = input('Job position: ')
    job_description = input('Job description: ')
    
    my_name = input('your name: ')
    my_phone = input('your phone number: ')
    my_email = input('your email: ')
    date = input('the date: ')
    
    return company_name, company_description, company_email,job_position, job_description, my_name, my_phone, my_email, date

# Converts the CV file to Base64 format before sending it to the Gemini API
def get_cv_base64():
    with open('cv.PDF', 'rb') as f:
        cv_bytes = f.read()
        cv_base64 = base64.b64encode(cv_bytes).decode('utf-8')
    return cv_base64

# Generates a personalized cover letter using the Gemini API
def get_cover_latter(company_name, company_description, job_description, date, cv_base64, GEMINI_API_KEY, prompt):
    gemini_url = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent'
    headers = {'content-type' : 'application/json', 'x-goog-api-key' : GEMINI_API_KEY}

    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt},
                    {'inline_data' : {'mime_type' : 'application/pdf','data' : cv_base64}},
                ]
            }
        ]
    }
    for attempt in range(3):
        ai_text = None
        try:
            response = requests.post(gemini_url, headers=headers, json=data)
            response.raise_for_status()
            ai_text =  response.json()['candidates'][0]['content']['parts'][0]['text']
            break
        except requests.exceptions.RequestException as e:
            print(f'API request failed: {e}')
    return ai_text

# Creates a PDF file from the cover letter text generated by Gemini
def get_cl_pdf(cover_latter):
    pdf_cl = "cl.pdf"
    doc = SimpleDocTemplate(pdf_cl, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()
    text = cover_latter.replace('\n', '<br/>')
    elements.append(Paragraph(text, styles['Normal']))
    doc.build(elements)

# send an email with the CV and cover letter attached
def get_send_email(company_email, job_position, my_name, my_email, my_phone, company_name, EMAIL_APP_PASSWORD):
    msg = EmailMessage()
    msg['From'] = my_email
    msg['To'] = company_email
    msg['Subject'] = f'Candidature au poste {job_position} - {my_name}'
    msg.set_content(f"Madame, Monsieur,\n\nJe vous adresse ma candidature pour le poste {job_position} au sein de {company_name}.\n\nVous trouverez ci-joint ma lettre de motivation ainsi que mon CV détaillant mon parcours académique et mon expérience professionnelle.\n\nJe reste à votre entière disposition pour tout complément d'information ou pour un entretien.\n\nDans l'attente de votre retour, je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées.\n\nCordialement,\n{my_name}\n{my_phone}\n{my_email}")
    with open('cl.pdf', 'rb') as f:
        file_data = f.read()
        msg.add_attachment(file_data, maintype='application',subtype='pdf', filename='cl.pdf')
    with open('cv.PDF', 'rb') as f:
        file_data = f.read()
        msg.add_attachment(file_data, maintype='application',subtype='pdf', filename='cv.pdf')  

    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(my_email, EMAIL_APP_PASSWORD)
    server.send_message(msg)
    server.quit()

company_name, company_description, company_email, job_position, job_description, my_name, my_phone, my_email, date = get_info() 
cv_base64 = get_cv_base64()
prompt = get_prompt(company_name, company_description, job_description, date)
cover_latter = get_cover_latter(company_name, company_description, job_description, date, cv_base64, GEMINI_API_KEY, prompt)
get_cl_pdf(cover_latter)
get_send_email(company_email, job_position, my_name, my_email,my_phone, company_name, EMAIL_APP_PASSWORD)